// <auto-generated />
using System;
using FoodDeliveryAppV1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDeliveryAppV1.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FoodDeliveryAppV1.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdminId");

                    b.ToTable("admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            Email = "admin@example.com",
                            Name = "SuperAdmin",
                            Password = "admin@123",
                            PhoneNumber = "1234567890",
                            Role = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("FoodDeliveryAppV1.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street",
                            CustomerName = "John Doe",
                            Email = "john@example.com",
                            PhoneNumber = "9876543210",
                            password = "john@123"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 South Avenue",
                            CustomerName = "Jane Smith",
                            Email = "jane@example.com",
                            PhoneNumber = "5554443322",
                            password = "jane@123"
                        });
                });

            modelBuilder.Entity("FoodDeliveryAppV1.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.ToTable("items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Description = "Classic cheese pizza",
                            IsAvailable = true,
                            ItemName = "Margherita Pizza",
                            Price = 9.99m
                        },
                        new
                        {
                            ItemId = 2,
                            Description = "Delicious burger with veggie patty",
                            IsAvailable = true,
                            ItemName = "Veggie Burger",
                            Price = 7.49m
                        },
                        new
                        {
                            ItemId = 3,
                            Description = "Pizza with pepperoni toppings",
                            IsAvailable = true,
                            ItemName = "Pepperoni Pizza",
                            Price = 10.99m
                        },
                        new
                        {
                            ItemId = 4,
                            Description = "Juicy chicken burger",
                            IsAvailable = true,
                            ItemName = "Chicken Burger",
                            Price = 8.49m
                        },
                        new
                        {
                            ItemId = 5,
                            Description = "Crispy golden fries",
                            IsAvailable = true,
                            ItemName = "French Fries",
                            Price = 3.49m
                        });
                });

            modelBuilder.Entity("FoodDeliveryAppV1.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDateTime = new DateTime(2025, 10, 13, 0, 10, 0, 0, DateTimeKind.Local),
                            Price = 9.99m,
                            Status = 1
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDateTime = new DateTime(2025, 10, 13, 0, 25, 0, 0, DateTimeKind.Local),
                            Price = 7.49m,
                            Status = 2
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 1,
                            OrderDateTime = new DateTime(2025, 10, 13, 0, 32, 0, 0, DateTimeKind.Local),
                            Price = 10.98m,
                            Status = 2
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 2,
                            OrderDateTime = new DateTime(2025, 10, 13, 0, 45, 0, 0, DateTimeKind.Local),
                            Price = 10.99m,
                            Status = 1
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 2,
                            OrderDateTime = new DateTime(2025, 10, 13, 0, 45, 0, 0, DateTimeKind.Local),
                            Price = 10.98m,
                            Status = 3
                        },
                        new
                        {
                            OrderId = 6,
                            CustomerId = 1,
                            OrderDateTime = new DateTime(2025, 10, 13, 0, 50, 0, 0, DateTimeKind.Local),
                            Price = 10.99m,
                            Status = 3
                        });
                });

            modelBuilder.Entity("FoodDeliveryAppV1.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"), 1L, 1);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("orderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            ItemId = 1,
                            OrderId = 1,
                            Quantity = 1,
                            UnitPrice = 9.99m
                        },
                        new
                        {
                            OrderItemId = 2,
                            ItemId = 2,
                            OrderId = 2,
                            Quantity = 1,
                            UnitPrice = 7.49m
                        },
                        new
                        {
                            OrderItemId = 3,
                            ItemId = 2,
                            OrderId = 3,
                            Quantity = 1,
                            UnitPrice = 7.49m
                        },
                        new
                        {
                            OrderItemId = 4,
                            ItemId = 5,
                            OrderId = 3,
                            Quantity = 1,
                            UnitPrice = 3.49m
                        },
                        new
                        {
                            OrderItemId = 5,
                            ItemId = 3,
                            OrderId = 4,
                            Quantity = 1,
                            UnitPrice = 10.99m
                        },
                        new
                        {
                            OrderItemId = 6,
                            ItemId = 2,
                            OrderId = 5,
                            Quantity = 1,
                            UnitPrice = 7.49m
                        },
                        new
                        {
                            OrderItemId = 7,
                            ItemId = 5,
                            OrderId = 5,
                            Quantity = 1,
                            UnitPrice = 3.49m
                        },
                        new
                        {
                            OrderItemId = 8,
                            ItemId = 3,
                            OrderId = 6,
                            Quantity = 1,
                            UnitPrice = 10.99m
                        });
                });

            modelBuilder.Entity("FoodDeliveryAppV1.Models.Order", b =>
                {
                    b.HasOne("FoodDeliveryAppV1.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FoodDeliveryAppV1.Models.OrderItem", b =>
                {
                    b.HasOne("FoodDeliveryAppV1.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDeliveryAppV1.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodDeliveryAppV1.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodDeliveryAppV1.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
